Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports DevExpress.DataAccess
Imports DevExpress.DashboardCommon

Namespace NewProject
	Partial Public Class Dashboard1
		Inherits DevExpress.DashboardCommon.Dashboard

		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			dashboardObjectDataSource2.DataSource = New System.ComponentModel.BindingList(Of NewProject.Data)() ' TODO: Assign the real data here.
		End Sub
	End Class
End Namespace
