using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevExpress.DataAccess;
using DevExpress.DashboardCommon;

namespace NewProject
{
    public partial class Dashboard1 : DevExpress.DashboardCommon.Dashboard
    {
        public Dashboard1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            dashboardObjectDataSource2.DataSource = new System.ComponentModel.BindingList<NewProject.Data>() /* TODO: Assign the real data here.*/;
        }
    }
}
